from pathlib import Path

TEMPLATE = '''\
"""
ctx_pipeline.py — generated by ctx-capture init

Fill in each stage with your pipeline's function calls.
Capture calls are pre-positioned. Do not move them.
"""

import ctxrun  # noqa: F401  (install: pip install ctx-capture)

def run_pipeline(query: str) -> str:

    run = ctxrun.start(query=query, pipeline="my_project")

    # --- Stage 1: Retrieval ---
    # chunks = your_retriever.retrieve(query)
    # run.chunks(chunks)

    # --- Stage 2: Context assembly ---
    # prompt, budget = your_assembler.assemble(chunks, history)
    # run.context(prompt, budget)

    # --- Stage 3: History management ---
    # run.history(pre=history_before, post=history_after, reason="token_budget")

    # --- Stage 4: LLM call ---
    # response = your_llm_client.call(prompt)
    # run.response(response)

    # run.commit() is called automatically after run.response()
    # call it explicitly here only if you skip run.response()
    # run.commit()

    return response  # noqa: F821
'''


def generate_scaffold(output_path: Path | None = None) -> Path:
    if output_path is None:
        output_path = Path.cwd()
    target = output_path / "ctx_pipeline.py"
    if target.exists():
        raise FileExistsError(
            f"{target} already exists. Remove it first if you want to regenerate."
        )
    target.write_text(TEMPLATE, encoding="utf-8")
    return target
